sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 990621
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRJEc2QG7whNeaj72JM
    access-key-secret: cScQf1pxIeyic2q3G0QQZOFg80lkLI
    bucket-name: web-takeout-227
  redis:
    database: 0
    host: localhost
    port: 6379
  wechat:
    appid: wx91a04b2f9c638194
    secret: 7ecf11a0628055fa14b040bdcd5cf464